# Generated by /home/bbrown/src/openjdk/openjdk6_test/hotspot/make/linux/makefiles/buildtree.make
if (! $?JAVA_HOME) setenv JAVA_HOME "/usr/lib/jvm/java-6-openjdk"
setenv LD_LIBRARY_PATH .:${JAVA_HOME}/jre/lib/i386/native_threads:${JAVA_HOME}/jre/lib/i386:
setenv CLASSPATH .:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/i18n.jar
setenv HOTSPOT_BUILD_USER "bbrown in hotspot"
