package org.berlin.euler;

import junit.framework.TestCase;
import junit.textui.TestRunner;

public class Euler12 extends TestCase {

    public long sumToN(final long n) {
        
        long sum = 0;
        for (long i = 1; i <= n; i++) {
            sum += i;         
        }
        return sum;
    }
    
    public int factorList(final long n) {
        
        long a = System.currentTimeMillis();
        final long triangle = this.sumToN(n);
        long b = System.currentTimeMillis();
        long diff = b - a;
        
        System.out.println("Triangle: " + triangle + " time to tri: " + diff);
        long calculations = 0;
        int count = 0;
        long c = System.currentTimeMillis();
        long z = c;
        for (long i = 1; i <= triangle; i++) {            
            if ((triangle % i) == 0) {
                z = System.currentTimeMillis();
                count++;
                System.out.println("{" + count + "} " + i + " proc=" + (z - c));
            }
            calculations++;
            
        } // End of the for //
        
        long d = System.currentTimeMillis();
        System.out.println("\n\n~!!! time to count: " + (d - c) + " calcs=" + calculations);
        System.out.println("===<< END OF N: " + n +  "\n\n");
        return count;
    }
    
    /**
     * Euler 12.
     * The sequence of triangle numbers is generated by adding the natural numbers. 
     * So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
     * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
     * @param args
     */
    public void euler12() {        
                
        int max = 0;
        for (int i = 1; i < 95000000; i++) {
            int ct = factorList(i);
            System.out.println("##### CURRENT_MAX " + max);
            if (ct > max) {
                max = ct;
                System.out.println("#####");
                System.out.println("##### MAX " + max);
                System.out.println("#####");
            }
            
            if (ct > 500) {
                System.out.println("Here is the COUNT!");
                break;
            }
        } // End of the for //
    }
    
    public void test1() {
        euler12();
    }
    
    public static void main(String [] args) {
             
        TestRunner.run(Euler12.class);
        
    }
    
} // End of the Class //
