/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sorter */

#ifndef _Included_Sorter
#define _Included_Sorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sorter
 * Method:    sort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Sorter_sort
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
