# Generated by /home/bbrown/src/openjdk/openjdk6_test/hotspot/make/linux/makefiles/buildtree.make
: ${JAVA_HOME:=/usr/lib/jvm/java-6-openjdk}
LD_LIBRARY_PATH=.:${JAVA_HOME}/jre/lib/i386/native_threads:${JAVA_HOME}/jre/lib/i386:
CLASSPATH=.:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/i18n.jar
HOTSPOT_BUILD_USER="bbrown in hotspot"
export JAVA_HOME LD_LIBRARY_PATH CLASSPATH HOTSPOT_BUILD_USER
