#!/bin/sh
#
# Berlin Brown
# bigbinc@hotmail.com
# $Id: com,v 1.4 2004/05/13 21:43:45 bigbinc Exp $
#
# use this for updates, 
#
export CVS_RSH=ssh

MSG="map2d"

cvs commit -m "$MSG"
cvs update -dP
